version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cloud-storage-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cloud_storage
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: 'redis:alpine'
    container_name: cloud_storage_redis
    ports:
      - '6379:6379'
    command: redis-server --protected-mode no
    labels:
      org.springframework.boot.ignore: true

volumes:
  postgres_data: