version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: cloud-storage-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: cloud_storage
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: Europe/Moscow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: 'redis:alpine'
    container_name: cloud_storage_redis
    ports:
      - '6379:6379'
    command: redis-server --protected-mode no
    environment:
      TZ: Europe/Moscow
    restart: always

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    container_name: cloud-storage-rabbitmq
    command: /bin/sh -c "rabbitmq-plugins enable --offline rabbitmq_stomp rabbitmq_web_stomp && rabbitmq-server"
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

    restart: always

  backend:
    build: .
    container_name: cloud-storage-backend
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_started
      minio:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cloud_storage
      SPRING_DATA_REDIS_HOST: redis
      SPRING_SESSION_REDIS_HOST: redis
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_STOMP_HOST: rabbitmq
      SPRING_RABBITMQ_STOMP_PORT: 61613
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
      MINIO_URL: ${MINIO_URL}
      MINIO_EXTERNAL_URL: ${MINIO_EXTERNAL_URL}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      TZ: Europe/Moscow
    restart: always

  frontend:
    build: ./frontend
    container_name: cloud-storage-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always

volumes:
  postgres_data:
  minio_data: