server:
  forward-headers-strategy: framework
spring:
  jpa:
    open-in-view: false
  application:
    name: CloudStorage

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile

  datasource:
    url: jdbc:postgresql://localhost:5432/cloud_storage
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 15
      minimum-idle: 10
      connection-timeout: 30000

  session:
    store-type: redis
    timeout: 30m
    redis:
      namespace: spring:session

  data:
    redis:
      host: localhost
      port: 6379

  flyway:
    enabled: true
    baseline-on-migrate: true

  rabbitmq:
    host: localhost
    port: 5672
    stomp:
      host: localhost
      port: 61613
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        prefetch: 1
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  tomcat:
    max-parameters: 10000          # Максимальное количество параметров в HTTP запросе.

  servlet:
    multipart:
      max-file-size: 1GB           # Максимальный размер одного загружаемого файла.
      max-request-size: 1GB        # Максимальный размер всего multipart запроса

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost/files}
  search:
    limit: 50                     # Максимальное количество результатов поиска.
  upload:
    max-files-per-request: 10000  # Максимальное количество файлов в одном запросе на загрузку
  archive:
    expiration-hours: 24          # Время жизни архива и ссылки по ТЗ
    executor:                     # Настройки пула потоков для архивации
      core-pool-size: 2
      max-pool-size: 5
      queue-capacity: 50


minio:
  url: ${MINIO_URL:http://localhost:9000}
  external-url: ${MINIO_EXTERNAL_URL:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  buckets:
    user-files: user-files
    temp-archives: temp-archives