CREATE TABLE users (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     username VARCHAR(255) NOT NULL UNIQUE,
     password VARCHAR(255),
     role VARCHAR(50) NOT NULL DEFAULT 'ROLE_USER',
     provider VARCHAR(50) NOT NULL DEFAULT 'LOCAL'
);

ALTER TABLE users
    ADD CONSTRAINT check_password_nullable
        CHECK (
            (provider = 'LOCAL' AND password IS NOT NULL)
                OR
            (provider = 'GOOGLE')
            );

CREATE INDEX idx_users_username ON users(username);